- name: change gc git version
  ansible.builtin.shell: |
    pm2 delete ~/ant-bu/ecosystem.config.js --only gc || true
    git fetch --all
    git checkout {{ ant_gc_version }}
    npm i
    npm run build
    pm2 start ~/ant-bu/ecosystem.config.js --only gc
  args:
    chdir: ~/ant-gc  #指定目錄
  when: ant_gc_version != ""
  #ignore_errors: true  #忽略錯誤

- name: check ant-gc current git version
  ansible.builtin.shell: |
    git branch
  args:
    chdir: ~/ant-gc
  changed_when: false #指定目錄
  when: ant_gc_version != ""